comments:
  lineComment: //
  blockComment:
    - '/*'
    - '*/'
brackets:
  -
    - '{'
    - '}'
  -
    - '['
    - ']'
  -
    - (
    - )
autoClosingPairs:
  -
    - '{'
    - '}'
  -
    - '['
    - ']'
  -
    - (
    - )
  -
    open: '"'
    close: '"'
    notIn: [string, comment]
  -
    open: ''''
    close: ''''
    notIn: [string, comment]
  -
    open: '`'
    close: '`'
    notIn: [string, comment]
  -
    open: '/**'
    close: ' */'
    notIn: [string]
surroundingPairs:
  -
    - '{'
    - '}'
  -
    - '['
    - ']'
  -
    - (
    - )
  -
    - '"'
    - '"'
  -
    - ''''
    - ''''
  -
    - '`'
    - '`'
indentationRules:
  increaseIndentPattern: ((\b(case|default|do|else|for|function|if|object|repeat|script|switch|while)\b((?!\b(elseif|else|end|endscript|until)\b).)*)|(\{\s*))$
  decreaseIndentPattern: ^\s*((\b(else|elseif|end|endscript|until)\b)|(\})|(\)))
folding:
  markers:
    start: \b(do|if|function|object|repeat|script|while)\b|#(ifdef|ifndef)\b|{[ \t]*$
    end: (\bend|endscript|until|#endif)\b|^\s*}
